allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
patchedDependencies:
  '@keystatic/astro@5.0.6': patches/@keystatic__astro@5.0.6.patch
